swagger: "2.0"
info:
  description: "iqas - Intelligent Question Answering System"
  version: "1.0.0"
  title: "Intelligent Question Answering System"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api"
tags:
- name: "Knowledge Base"
  description: "Access to knowlegde base"
- name: "Answer Retreival"
  description: "Access to answer retrival"
schemes:
- "https"
- "http"
paths:
  /kb:
    get:
      tags:
      - "Knowledge Base"
      summary: "Get all knowledge bases"
      produces:
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/knowledgeBase"
        "400":
          description: "Invalid status value"
    
    post:
      tags:
      - "Knowledge Base"
      summary: "Add a new Knowledge Base"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "body of Knowledge base"
        required: true
        schema:
          $ref: "#/definitions/knowledgeBase"
      responses:
        "201":
          description: "Created"
      
  /kb/{id}:
    put:
      tags:
      - "Knowledge Base"
      summary: "Edit a Knowledge Base by id"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Knowledge source object's body"
        required: true
        schema:
          $ref: "#/definitions/knowledgeBase"
      - name: "id"
        in: "path"
        description: "KB id to update"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
    delete:
      tags:
      - "Knowledge Base"
      summary: "Deletes a KB"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "KB id to delete"
        required: true
        type: "string"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
      
  /kb/{kbId}/doc:
    post:
      tags:
      - "Knowledge Base"
      summary: "Finds Pets by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findPetsByStatus"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/document"
      - name: "kbId"
        in: "path"
        description: "kb to be answered"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/document"
        "400":
          description: "Invalid status value"
  /ar/kb/{kbId}:
    post:
      tags:
      - "Answer Retreival"
      summary: "Answer Retrival post call"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "question"
        in: "body"
        description: "Question to be answered"
        required: true
        schema:
          type: "string"
      - name: "kbId"
        in: "path"
        description: "kb to be answered"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid tag value"
definitions:
  knowledgeBase:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
  document:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      text:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
